### PR TITLE
generate state and difficulty tests

### LINKED ISSUE #6: Missing default values for precondition fields
To maintain compatibility with ETH tests, precondition fields should have default values according to the following table 
| Field | ETH default value |
| - | - |
| _nonce_  | `"0x0" \| "0x00"`  |
| _balance_  | `"0x0" \| "0x00"`  |
| _code_ | `"0x"`|
| _storage_ | `{ }`|

### PR DESCRIPTION
**Pull request by meowsbits**
Tests filled using the new difficulty test schema; with `parentUncles` now being a `uint64` instead of a `hash`, where the number value is how many uncles the parent has (either `0x0` or `0x1`). 
Generated tests now also include filling `_info` too.

etclabscore/core-geth filling version:
- branch: https://github.com/etclabscore/core-geth/commits/merge/foundation-release/1.10.23-tests-generate-fixes-statefix-difficulty-test-v2
- head: https://github.com/etclabscore/core-geth/commit/e7f7eff69ebd4ffc5a66fa87ad12f798fa8545bb

Fixes #6

### CODE REVIEW

**Review by diega — CHANGES_REQUESTED** [review]
can we make them `0x00` and `0x01`? That's how they are defined in the ETH tests and there is some logic already in Besu for handling that case (ref.: [`o.h.b.e.m.DifficultyCalculatorTests:175`](https://github.com/hyperledger/besu/blob/22.7.4/ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/mainnet/DifficultyCalculatorTests.java#L175))
```shell
ethereum/tests/DifficultyTests $ find . -name \*.json -exec jq '..|.parentUncles?' {} + | sort | uniq -c                                                                                                                       git:(638da7ca7b|)
9301 "0x00"
9297 "0x01"
  68 null
```

**Comment by meowsbits** [comment]
In addition to the change decribed in the [OP](https://github.com/etclabscore/tests-etc/pull/4#issue-1387949079), subsequent commits now also do:

- https://github.com/etclabscore/tests-etc/pull/4/commits/5609a9c9047424aee57097a22c56825fdd7a1040 removes the "moving target" `ETC` configuration difficulty tests, and adds a missing test for `ETC_Magneto`.
- https://github.com/etclabscore/tests-etc/pull/4/commits/eee0383834a6e32ff17690d6c4763fffd04fcaaa re: state tests; encodes state accounts (used at state "pre" allocations) to always include `code`, `balance`, and `nonce` fields, even if they're zero values. `storage` is (still) optional and is omitted when empty. This seems to comply with the JSON schema defined in _ethereum/tests#JSONSchema/st-schema.json_.

**Comment by meowsbits** [comment]
And in reply to @diega's https://github.com/etclabscore/tests-etc/pull/4#pullrequestreview-1124333122, we've decided that the encoding as `0x0` and `0x1` (with no zero-padding) is acceptable per the spec, as discussed in #6.

**Review by diega — APPROVED** [review]
LGTM!

**Pull request merged**
